Added  energy.orbint.correction
TheoChem-VU/TCutility pull request #250
Opened 2024-05-24 11:01 UTC by ToriGijzen

Added property for energy.orbint.correction

2024-05-25 14:13 UTC, SiebeLeDe reviewed
I think there's something going wrong here because "symlabel" is not defined outside the loop.

2024-05-27 08:53 UTC, ToriGijzen commented
> I think there's something going wrong here because "symlabel" is not defined outside the loop.

Yes this was my template/note for myself what to do. It is not done, yet.

2024-05-28 10:15 UTC, SiebeLeDe approved these changes

2024-05-28 14:09 UTC, YHordijk commented on src/tcutility/results/adf.py
Add an explanation of the correction term

2024-05-28 14:10 UTC, YHordijk requested changes
Only the docstring thing

2024-07-17 10:11 UTC, merged