20 adding vibration mode analysis
TheoChem-VU/TCutility pull request #40
Opened 2023-10-12 13:01 UTC by ksalimans

Transition state validation using vibrations

2023-10-12 13:07 UTC, YHordijk commented on TCutility/analysis/ts_vibration.py
Instead of atom_distance, use built-in plams.Atom.distance_to function

2023-10-12 13:20 UTC, YHordijk commented on TCutility/analysis/ts_vibration.py
> +    return (x+y)/2
Also for small functions add docstrings and place comments in the code itself

2023-10-12 13:20 UTC, YHordijk commented on TCutility/analysis/ts_vibration.py
> +    assert 'modes' in data.properties.vibrations, 'Vibrational data is required, but was not present in .rkf file'
Also check if the frequencies are imaginary. Or you could loop through all modes that have imaginary frequencies and return a list of lists

2023-10-12 13:22 UTC, YHordijk commented on TCutility/analysis/ts_vibration.py
> +    assert 'modes' in data.properties.vibrations, 'Vibrational data is required, but was not present in .rkf file'
Add an argument to select a normal mode to analyse (default to 0). Also add a new function that analyses all imaginary vibrations for a given molecule

2023-10-12 13:29 UTC, YHordijk commented on TCutility/analysis/ts_vibration.py
> +def validate_transitionstate(calc_dir: str, rcatoms = None, bond_tolerance: float = 1.28, min_delta_dist: float = 0.1) -> bool:
Put a **kwargs in the function definition. Add a link :func:`determine_ts_reactioncoordinate` to the docstring

2023-10-12 13:33 UTC, YHordijk commented on TCutility/analysis/ts_vibration.py
> +def validate_transitionstate(calc_dir: str, rcatoms = None, bond_tolerance: float = 1.28, min_delta_dist: float = 0.1) -> bool:
Instead of checking if the provided RC is equal to the predicted RC, check if the provided RC is a member of the predicted RC

2023-10-12 13:36 UTC, YHordijk commented on TCutility/analysis/ts_vibration.py
> +    if isinstance(rcatoms, list):
Use https://numpy.org/doc/stable/reference/generated/numpy.atleast_2d.html for this

2023-10-12 13:40 UTC, YHordijk commented on TCutility/analysis/ts_vibration.py
> +        assert 'reactioncoordinate' in data.input.transitionstatesearch, 'Reaction coordinate is a required input, but was neither provided nor present in the .rkf file'
Check if the reactioncoordinate is a "Distance" and not "Angle" or "Dihedral"

2023-10-12 13:43 UTC, YHordijk commented on TCutility/analysis/ts_vibration.py
> +    result[:, 2] = result[:, 2] if np.sign(result[0][2]) == rcatoms[0][2] else -result[:, 2]
Only check if the sign is correct if it is given in rcatoms in the arguments. Otherwise skip it

2023-10-12 13:50 UTC, YHordijk commented on TCutility/analysis/ts_vibration.py
> +if __name__ == '__main__':
Add these to the test-suit too

2023-10-12 13:51 UTC, YHordijk commented on TCutility/results/adf.py
> +    else:
Add an explanatory comment

2023-10-12 13:52 UTC, YHordijk commented on TCutility/analysis/ts_vibration.py
> +from TCutility.results import read
Import results from TCutility and then call read as results.read for clarity

2023-10-12 13:52 UTC, YHordijk commented on TCutility/analysis/ts_vibration.py
> +        data = read(calc_dir)
Call read as results.read

2023-10-12 13:53 UTC, SiebeLeDe commented on TCutility/results/ams.py
Nice! Good fix

2023-10-12 13:53 UTC, SiebeLeDe commented on TCutility/results/adf.py
I see that you want to do multiple things here:
1. Have a default value for symmetry point group and label
2. Only read 

In what cases is there no symmetry -> symlab or geometry -> grouplabel section in the adf.rkf? So far as I know, it is always present.

If you can show me an example, then I'm convinced. The problem is then that the if/else statement 

```
    if ('Symmetry', 'symlab') in reader_adf:
        ret.symmetry.labels = reader_adf.read('Symmetry', 'symlab').strip().split()
    else:
        ret.symmetry.labels = ['A'] 
```
might crash the program. A safer way is to use a try/except statement 

    try:
        ret.symmetry.labels = reader_adf.read('Symmetry', 'symlab').strip().split()
    except [TYPE_OF_ERROR]:
        ret.symmetry.labels = ['A']

2023-10-12 13:53 UTC, SiebeLeDe commented on TCutility/analysis/ts_vibration.py
Also, please give the format of "reaction_coordinate"
Is it like [Atom1, Atom2, angle/distance ...?]

Btw, file = '../../test/fixtures/radical_addition_ts' works not for me when I use the "review in codespace" functionality in git. 

![Screenshot 2023-10-12 at 15 39 00](https://github.com/TheoChem-VU/TCutility/assets/77436462/d46ca844-418c-4a68-b4b9-d7a746e241aa)

This error originates from the Result dict being empty, which becomes TOTALLY NOT CLEAR from the error message itself.

2023-10-12 13:56 UTC, YHordijk requested changes
If you change the feedback, I think it is ready to be added to TCutility

2023-10-13 13:53 UTC, ksalimans commented on TCutility/analysis/ts_vibration.py
I added documentation for the reaction coordinate format. Cannot reproduce the Result error in this case, but agreed that the error message will need to be clarified.

2023-10-13 19:47 UTC, ksalimans commented on TCutility/analysis/ts_vibration.py
> +                return False
```suggestion
                ret.append(False)
                continue
```

2023-10-13 19:47 UTC, ksalimans commented on TCutility/analysis/ts_vibration.py
> +        rcatoms: list or array containing expected reaction coordinates, to check against the transition state. If not defined, it is obtained from the ams.rkf user input. Only uses 'Distance' reacti
```suggestion
        rcatoms: list or array containing expected reaction coordinates, to check against the transition state. If not defined, it is obtained from the ams.rkf user input. 
        Only uses 'Distance' reaction coordinate. Format should be [atomlabel1, atomlabel2, (optional) sign]
```

2023-10-14 07:34 UTC, YHordijk commented on TCutility/analysis/ts_vibration.py
I created issue #41 to fix this, it is not in the scope of Koen's PR

2023-10-16 12:48 UTC, YHordijk commented on TCutility/results/adf.py
We originally had this because in our ML database we are pruning the rkf files to reduce file size, including pruning of symmetry information. Now I am thinking it might instead be better to just re-add it and keeping TCutility clean. I support expecting the rkf file to have the symmetry information and I think we should just remove setting a default value.

2023-10-19 14:13 UTC, YHordijk approved these changes

2023-10-24 12:46 UTC, merged