simple job running api
TheoChem-VU/TCutility pull request #89
Opened 2024-01-23 09:25 UTC by YHordijk

This PR will bring the job API. It is still a draft for now, as I am still working on it.

2024-01-27 19:38 UTC, SiebeLeDe requested changes

2024-01-27 19:38 UTC, SiebeLeDe commented on src/tcutility/data/available_functionals.txt
Wat vaker voorkomt is dit in een .json of .toml format te schrijven zodat het makkelijk in te lezen of te veranderen is als het project groter groeit. Het is meer met oog op de toekomst voor als anderen deze package willen integreren met andere talen (bijvoorbeeld voor betere sitedocumentatie met typescript)

2024-01-27 19:38 UTC, SiebeLeDe commented on docs/_build/doctrees/__modules.doctree
_build should be ignored by git since it is made automatically. We only change things in the docs and static. Can you add */_build to the .gitignore?

2024-01-27 19:38 UTC, SiebeLeDe commented on src/tcutility/data/molecules.py
Why check for .DS_Store? All molecules should have .xyz as extension

2024-01-27 19:38 UTC, SiebeLeDe commented on src/tcutility/job/adf.py
Can you add a validation of the functional and settings as well in order to prevent silly and annoying errors. This is one of the main drawbacks of the Plams settings if you only use plams: you have no idea what correct options are and if your job will result in an error.

2024-01-27 19:38 UTC, SiebeLeDe commented on src/tcutility/results/ams.py
I added this also in the vdd pull request as "mol_charge"

2024-01-28 19:30 UTC, YHordijk commented on docs/_build/doctrees/__modules.doctree
It should already be added (https://github.com/TheoChem-VU/TCutility/blob/c8e00efbb839825e5c5869cbe556aeed6e99d80d/.gitignore#L72). I am not sure why the _build is still in the repo. Perhaps we first have to remove them again.

2024-01-28 19:33 UTC, YHordijk commented on src/tcutility/data/molecules.py
I have changed it so it now checks for .xyz instead

2024-01-28 19:49 UTC, YHordijk commented on src/tcutility/data/available_functionals.txt
Dat is inderdaad een goed idee. Ik heb voor nu een [script](https://github.com/TheoChem-VU/TCutility/blob/a962a7b642b45e1b80b3dd898595eb94847ce627/src/tcutility/data/_convert_to_json.py) toegevoegd dat de informatie over functionalen omschrijft in een json bestand. Ik weet niet of een json of toml bestand veel makkelijker te gebruiken is voor onze doeleinden (json bestand is 4064 lijnen, txt bestand is 227). Als we iets veranderen kunnen we simpelweg het scriptje runnen.

2024-01-28 19:50 UTC, YHordijk commented on src/tcutility/results/ams.py
I will remove the change in this branch! It is not relevant to the linked issues anyway.

2024-01-28 20:02 UTC, YHordijk commented on src/tcutility/job/adf.py
Right now, if you give the wrong functional it will give you a warning, but it will still assign it to the `LibXC` key. Probably it will crash later on if you made a typo. We can implement the [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) to make suggestions to the user for functionals that have similar names. 
In any case, I am also fine with letting the job crash completely if an unrecognized functional is given. We can then add a `libxc` argument to the `job.functional` method for people who want to use a functional using LibXC.

For the rest of the settings they should in principle always be good as we are setting the correct keys using the class methods. If the user manually sets the settings in the `job.settings` property there is a chance the job will fail. I don't really know of a way to check beforehand if the job will run or not.

I think the largest source of error right now is typo's by the user. For example, the `job.basis_set` method does not check if the value is correct. The same goes for pretty much all other methods besides the `job.functional` method.

2024-01-29 19:05 UTC, SiebeLeDe commented on src/tcutility/data/available_functionals.txt
json is handiger omdat het in één keer te laden is waaruit je een dict krijgt. json is een standaardlibrary in meerdere talen waaronder python waardoor het robuuster is dan zelf een format schrijven.

2024-01-29 19:06 UTC, SiebeLeDe commented on docs/_build/doctrees/__modules.doctree
I think so too

2024-01-29 19:10 UTC, SiebeLeDe commented on src/tcutility/job/adf.py
We can add like "validate_user_input" in the generic job class that is always called upon running a job and have the specific implementation in the inherited classes such as ADFJob. We can start with the ADFJob class and have all available basis sets, num. quality, and functionals stored somewhere. We just need to check if the user input matches with any of the arguments. If not, then a warning or error is raised. 

Í dont think it's worth the time now to implement the Levenshtein distance. If you have time left over, you can try it. Otherwise, we just leave it by saying to the user that their input is wrong and list the available options.

2024-01-30 10:31 UTC, YHordijk commented on src/tcutility/job/adf.py
I will add the Levenshtein distance in a separate PR and implement validation there too.

2024-01-30 10:39 UTC, merged